### PR TITLE
Make implicit clock and reset final vals

### PR DESCRIPTION
**Pull request by jackkoenig**
Overriding will always result in a `NullPointerException` due to https://github.com/freechipsproject/chisel3/blob/aac6e175645960b65eace70d16d0e4df523e0327/chiselFrontend/src/main/scala/chisel3/RawModule.scala#L155 which 

This is definitely not source compatible, so I don't think we should backport it. Although if someone is doing this it cannot be a Module they ever actually construct because it's `NullPointerException` 100% of the time.

**Related issue**: 

**Type of change**: bug fix

**Impact**: API modification

**Development Phase**: implementation

**Release Notes**
Make implicit clock and reset final vals fixing buggy hole in API

### CODE REVIEW

**Comment by jackkoenig** [comment]
@freechipsproject/chisel-reviewers any opinions on this? Fixes a hole in the API

**Comment by sdtwigg** [comment]
Nit: it should still work if you use an early initializer so I don't think it is quite 100%

**Comment by jackkoenig** [comment]
> Nit: it should still work if you use an early initializer so I don't think it is quite 100%

Hey @sdtwigg! I honestly had forgotten about that feature. It does provide a potentially better way to express https://github.com/freechipsproject/chisel3/pull/1361, although perhaps esoteric...

**Comment by albert-magyar** [comment]
Deprecated in 2.14, too

**Comment by jackkoenig** [comment]
I believe `2.14` has been dropped, but they are removed from dotty, replaced by trait parameters which may provide a better mechanism anyway: https://dotty.epfl.ch/docs/reference/dropped-features/early-initializers.html

I think it's worth reconsidering this and #1361 for longer term, but for the purposes of `3.3` I think this is best.

**Pull request merged**
