### PR TITLE
Revert "Interval Data Type Support for Chisel (#1210)"

### PR DESCRIPTION
**Pull request by ucbjrl**
This reverts commit 7b93b0f8c48e39cc9730cf9f91340cf733dadafe.

### CODE REVIEW

**Comment by jackkoenig** [comment]
It's failing due to the pulled FIRRTL SNAPSHOT: `sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:firrtl_2.12:1.2-20191030-SNAPSHOT`. I'm thinking release branches should build from release branches, so `3.2.x` should probably build FIRRTL from source and use that, alternatively it could depend on `1.2.+`, thoughts?

**Comment by ucbjrl** [comment]
Typically (in the past), I do all the tests by building from source locally (after deleting the edu.berkeley.cs ivy cache). I don't submit the dependency changes as PRs - I merge them directly into the Z.Y.x branch. They don't get CI testing. The dependencies (pretty much have to) reflect post-publishing.

I think reproducible builds are important so I'm hesitant to support wild cards in dependencies.

If we do want to have CI testing on release updates (which would be a good thing), I think it has to use build from source and publishLocal.

**Comment by jackkoenig** [comment]
I think we definitely want CI on release branches because I want to automate bugfix backporting to make bugfix releases as easy to do as possible. I agree with you about reproducibility, so does that mean we should test against FIRRTL `1.2.0` and bump that number each time we release a new FIRRTL?

Per Jenkins, is that configuration in the repo or is it defined elsewhere? Can you fix the chisel3 CI for `3.2.x` or is there some way I can help?

**Comment by ucbjrl** [comment]
It's defined in the Jenkins job, which does allow overriding dependency versions. I can manually push this through with the correct dependencies, but we should use structured comments to define them.
(i.e., Requires firrtl <pr ddd>|<branch abc>)

**Comment by jackkoenig** [comment]
Ideally there's no need for manual intervention at all if we want to automate backporting, can we make Jenkins treat release branches like 3.2.x differently than master?

**Comment by ucbjrl** [comment]
Yes. We can add branch-specific Jenkins job code.

**Pull request merged**
