### PR TITLE
Added MemShiftRegister to chisel utils

### PR DESCRIPTION
**Pull request by da-steve101**
Added a shift register implemented with a memory instead

### CODE REVIEW

**Comment by ucbjrl** [comment]
Ok to test.

**Comment by ucbjrl** [comment]
Please add some comments (scaladoc style) describing usage and parameters.

**Comment by edwardcwang** [comment]
This seems very similar to a Queue - is there a way you could use that construction instead?

**Comment by da-steve101** [comment]
I could use the Queue instead of a memory to implement it but i don't understand why I would. I would still need a wrapper around a Queue to implement the shift register and there would be additional overhead. Unless you are saying why add this to chisel when you can use a Queue?

**Comment by edwardcwang** [comment]
Well, how large are these shift registers which you would like to implement? It just seems a bit like such a shift register with delay n is essentially a Queue with depth n and always enqueueing.

**Comment by da-steve101** [comment]
If i used a Queue, instead of 1 Counter I would have 2. And then also have the logic to detect Full/Empty. I currently am working on an application that has unusually large SR but I agree that it wouldn't be that common.

**Comment by da-steve101** [comment]
Perhaps an official "chisel-utils" repo should be created similar to testers and this should go in there?

**Pull request closed without merging**
