### PR TITLE
Fix deprecation warning that leaks into user code

### PR DESCRIPTION
**Pull request by jackkoenig**
Data.isLit called Data.litArg which would trigger a Chisel runtime
deprecation warning in user code with source locator Data.scala:488

As reported in https://stackoverflow.com/questions/59049673/how-to-initialize-a-reg-of-bundle-in-chisel/59058082?noredirect=1#comment104418728_59058082

**Related issue**: 

**Type of change**: bug fix

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**
Fix internal deprecation warning on Data.isLit that leaked into user code

### CODE REVIEW

**Comment by jackkoenig** [comment]
@ucbjrl it seems that Jenkins is down. Did we decide to remove Jenkins from regular CI flow? Should we go ahead and remove it?

**Comment by ucbjrl** [comment]
Let's remove Jenkins from the PR flow.

**Comment by jackkoenig** [comment]
@ucbjrl can you or one of the other repo admins do it? It's somewhere in the repo settings

**Comment by ucbjrl** [comment]
I removed it. I'm not sure what else may be required. I'll squash and merge it once the CircleCI checks complete.

**Comment by jackkoenig** [comment]
Thanks Jim!!

**Comment by ucbjrl** [comment]
Unfortunately, this breaks dsptools since:
```scala
  override def litOption: Option[BigInt] = ???  // TODO implement me
```

```
[info] ComplexOpSpecification:
[info] 
[info]   The ParameterizedNumericOperation demonstrates a Module that can be instantiated to
[info]   handle different numeric types and different numerical operations
[info]   
[info]   This instance will process DspComplex[Real] numbers with the basic mathematical operations
Total FIRRTL Compile Time: 93.9 ms
[info]   - operation + should work for all inputs *** FAILED ***
[info]     firrtl.options.OptionsException: Exception thrown when elaborating ChiselGeneratorAnnotation
[info]     at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:55)
[info]     at chisel3.stage.phases.Elaborate$$anonfun$transform$1.apply(Elaborate.scala:19)
[info]     at chisel3.stage.phases.Elaborate$$anonfun$transform$1.apply(Elaborate.scala:18)
[info]     at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]     at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]     at scala.collection.immutable.List.foreach(List.scala:392)
[info]     at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
[info]     at scala.collection.immutable.List.flatMap(List.scala:355)
[info]     at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:18)
[info]     at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:16)
[info]     ...
[info]     Cause: scala.NotImplementedError: an implementation is missing
[info]     at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
[info]     at chisel3.Aggregate.litOption(Aggregate.scala:46)
[info]     at chisel3.Data.isLit(Data.scala:496)
[info]     at dsptools.numbers.DspComplex$.apply(DspComplex.scala:22)
```

**Comment by ucbjrl** [comment]
dsptools just wants to know if this is a lit; it doesn't care about its value. Perhaps we should have `isLit()` just return `true` if the binding is a literal?

**Comment by jackkoenig** [comment]
Why doesn't it care about the value? Should we instead implement `litOption`? `DspComplex` is a Bundle right? Can we use Bundle literals?

In any case, this may need to be reverted from `3.2.x` since it is not compatible without modification to DSP tools

**Comment by ucbjrl** [comment]
It's an optimization. Check out [DspComplex.scala](https://github.com/ucb-bar/dsptools/blob/master/src/main/scala/dsptools/numbers/chisel_concrete/DspComplex.scala)

**Comment by jackkoenig** [comment]
Oh I see, I guess alternatively we can just make `litOption` `None` for the things that can't be lits...

**Pull request merged**
