### PR TITLE
Remove checkboxes from issue/pr templates.

### PR DESCRIPTION
**Pull request by ucbjrl**
* **Type of change**
  Other enhancement

* **Impact**
  no functional change

* **Development Phase**
   implementation

### CODE REVIEW

**Comment by colinschmidt** [comment]
Nice. This would make it look more like my recent issue? I approve

**Comment by ducky64** [comment]
One comment on the use of bullet points for headings: it means users need to be careful about making responses sub-bullets, which I don't think everyone will. For example, note the formatting (indents and dashes) required in "Please tell us about your environment".

Here's what it currently looks like in GitHub




* **Type of issue**: bug report | feature request | other enhancement


* **Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown


* **Development Phase**: request | proposal

* **Other information**
 

* **If the current behavior is a bug, please provide the steps to reproduce the problem:**
  * **What is the current behavior?**
  * **What is the expected behavior?**
  * **Please tell us about your environment:**

* **What is the use case for changing the behavior?**

**Comment by ucbjrl** [comment]
Should we eliminate the bullet points? If we want a bot to tag the issue based on the categories in the PR, we need some sort of structured text to guide it.

**Comment by ducky64** [comment]
I'm not sure bullet points will provide that structure, especially if users aren't careful about consistently formatting to that structure. Also, shouldn't the section headings (in bold too) be sufficient to extract structure from it?

**Pull request merged**
