### PR TITLE
README: have a linke to the classic tutorial

### PR DESCRIPTION
**Pull request by schoeberl**
Link to an old but good tutorial for Chisel

### CODE REVIEW

**Comment by schoeberl** [comment]
The bootcamp is still first and recommended. I think that the offline tutorial is a nice resource that you can use offline without much installation effort.

**Comment by schoeberl** [comment]
Actually I wanted to add this link to chisel-lang.org. However, I have a hard time to find where the initial page is. @seldridge maybe you can give me a hint.

Martin

**Comment by seldridge** [comment]
@schoeberl: Currently the landing page _is_ the chisel3 README.md. There's some [`build.sbt` magic that will copy the `chisel3/README.md` living in a submodule into `index.md`](https://github.com/freechipsproject/www.chisel-lang.org/blob/36bcf18b5d033a2c205571ceaaee90307a6a148a/build.sbt#L45). So, updates made here will show up when the submodules get bumped.

**Comment by schoeberl** [comment]
Ok, great! So by coincidence I did the change at the right place :-)

Martin

**Comment by schoeberl** [comment]
Can someone merge? I do not have write access to this repo.

Martin

**Pull request merged**
