### PR TITLE
Add Chisel logo to repo and README

### PR DESCRIPTION
**Pull request by albert-magyar**
@seldridge @ucbjrl , this should make it easier for people to find.

### CODE REVIEW

**Comment by edwardcwang** [comment]
Can we have less spacing around the logo, or put it under the header?

**Comment by albert-magyar** [comment]
I switched to a cropped SVG, which will fix that space @edwardcwang. I also reverted the README changes; this way, I can add them back by referencing a raw Github content link directly to the vector version.

**Comment by seldridge** [comment]
Looks good. Anecdotally, I like the rebase/amend to get it down to one commit. However, at least with Travis, the jobs started in the rebase don't get killed. Jenkins may be doing the same thing here.

Also, what happened to CircleCI? @ucbjrl, I don't think it was turned off?

**Comment by albert-magyar** [comment]
Yeah, the real problem is that I kept pushing to my branch after I opened the PR to check the README formatting :(

**Comment by ucbjrl** [comment]
I think the issue is this is coming from a repo outside of freechipsproject. I'm not sure what needs to happen to get CircleCI to do its thing. I suspect this is a CircleCI bug.

**Comment by ucbjrl** [comment]
It looks like there's a setting in the CircleCI project which needs to be enabled to allow builds for pull requests from forks. I've enabled it for freechipsproject. Let's see if it requires another push to trigger.

**Comment by ucbjrl** [comment]
I tried redelivering the notification from GitHub but that doesn't seem effective. @albert-magyar could you push a gratuitous change to see if that will trigger CircleCI?

**Comment by albert-magyar** [comment]
Yeah, it did trigger it @ucbjrl

**Pull request merged**
