### PR TITLE
Fix build error due to scala bug #11125

### PR DESCRIPTION
**Pull request by nhynes**
JDK 11 `java.lang.String#lines` conflicts with Scala `StringOps#lines`.
This has been fixed in scalac 2.12.8 but projects using 2.11 in their
cross-build need the `Predef.augmentString` patch.

[Scala bug & fix reference](https://github.com/scala/bug/issues/11125)

### CODE REVIEW

**Comment by jackkoenig** [comment]
ok to test

**Comment by jackkoenig** [comment]
Oh yeah, I'm not an admin so I guess I can't make Jenkins run, @ducky64 or @ucbjrl, would you mind making Jenkins run?

**Comment by ducky64** [comment]
ok to test

**Comment by ucbjrl** [comment]
retest this please

**Pull request merged**
