### PR TITLE
Remove over design

### PR DESCRIPTION
**Pull request by colin4124**
**Type of change**: bug report

**Impact**: no functional changemodification

**Development Phase**:  implementation

**Release Notes**

 `rename` is private, and it only is called when  `names` contains new name string in method `def name` . Thus no need to use `getOrElse`

```scala
if (this contains sanitized) {
      name(rename(sanitized))
}
```

### CODE REVIEW

**Comment by ucbjrl** [comment]
ok to test

**Comment by edwardcwang** [comment]
Is there some performance benefit to doing this?

**Comment by colin4124** [comment]
@edwardcwang Maybe no

**Comment by albert-magyar** [comment]
@colin4124 can you sign the Contributor License Agreement?

https://cla-assistant.io/freechipsproject/chisel3

**Pull request merged**
