### PR TITLE
Trim Stack Trace

### PR DESCRIPTION
**Pull request by albertchen-sifive**
**Related issue**: 
https://github.com/freechipsproject/chisel3/issues/845
This is what the trimmed stack trace looks like (using the example from the issue). I only trimmed the top and bottom of the stack. Not sure about how the middle part should be filtered.
```
[info] [0.003] Elaborating design...
[error] chisel3.core.Binding$ExpectedChiselTypeException: reg type 'chisel3.core.UInt@3400978d' must be a Chisel type, not hardware
[error]         ...
[error]         at NeedChiselType.$anonfun$delays$1(ChiselExceptionTest.scala:8)
[error]         at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[error]         at NeedChiselType.<init>(ChiselExceptionTest.scala:8)
[error]         at NeedChiselTypeTop$.$anonfun$code$1(ChiselExceptionTest.scala:17)
[error]         at chisel3.core.Module$.do_apply(Module.scala:51)
[error]         at chisel3.Driver$.$anonfun$elaborate$1(Driver.scala:94)
[error]         at chisel3.internal.Builder$.$anonfun$build$2(Builder.scala:317)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error]         at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:315)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error]         at chisel3.internal.Builder$.build(Builder.scala:315)
[error]         at chisel3.Driver$.elaborate(Driver.scala:94)
[error]         at chisel3.Driver$.execute(Driver.scala:185)
[error]         at chisel3.Driver$.execute(Driver.scala:264)
[error]         at NeedChiselTypeTop$.delayedEndpoint$NeedChiselTypeTop$1(ChiselExceptionTest.scala:17)
[error]         at NeedChiselTypeTop$delayedInit$body.apply(ChiselExceptionTest.scala:16)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at NeedChiselTypeTop$.main(ChiselExceptionTest.scala:16)
[error]         at NeedChiselTypeTop.main(ChiselExceptionTest.scala)
[error]         ... (Stack trace trimmed to user code only, rerun with --full-stacktrace if you wish to see the full stack trace)
```

**Type of change**: feature request

**Impact**: no functional change?
This PR changes `Driver.execute` so that it catches `ChiselException` and returns `ChiselExecutionFailure` instead of letting them fall through. This affected `DontTouchSpec` which was looking for a binding exception to be thrown. not sure about what other affects this may have.

**Development Phase**: implementation

**Release Notes**

### CODE REVIEW

**Comment by seldridge** [comment]
ok to test

**Comment by seldridge** [comment]
I thought I had admin powers to start Jenkins... Apparently not...

**Comment by jackkoenig** [comment]
ok to test

**Comment by jackkoenig** [comment]
Guess I don't have the power either 🙁

**Comment by jackkoenig** [comment]
This looks really good. Once change I would suggest (and I'm soliciting opinions here) is that I would trim the bottom to be the first element on the stack in the user code within the context of Chisel.

For example, I would further trim the above to:
```
[info] [0.003] Elaborating design...
[error] chisel3.core.Binding$ExpectedChiselTypeException: reg type 'chisel3.core.UInt@3400978d' must be a Chisel type, not hardware
[error]         ...
[error]         at NeedChiselType.$anonfun$delays$1(ChiselExceptionTest.scala:8)
[error]         at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[error]         at NeedChiselType.<init>(ChiselExceptionTest.scala:8)
[error]         at NeedChiselTypeTop$.$anonfun$code$1(ChiselExceptionTest.scala:17)
[error]         ... (Stack trace trimmed to user code only, rerun with --full-stacktrace if you wish to see the full stack trace)
```

I think the trimming should look for the Builder (kind of the entry point for Chisel) and then trim until it finds the first piece of user code there. We're trying to give stack traces of stuff within Chisel code so I would ignore anything outside of the context of Chisel elaboration by default

**Comment by ucbjrl** [comment]
ok to test

**Comment by ucbjrl** [comment]
I think Jenkins has its own idea of who are  the admins. I'll try to update it.

**Comment by edwardcwang** [comment]
@ucbjrl Could we make it so all reviewers can ask Jenkins to rebuild?

**Comment by ucbjrl** [comment]
The existing GitHub pull request builder Jenkins plugin is being deprecated. I'll check out its replacement to see if there's a way to use GitHub teams to determine authorization.

**Comment by chick** [comment]
In response to @jackkoenig comment on the trimmed stack trace, I don't agree that Builder should be the start point, the test harness itself should definitely remain included in the stack trace, that tells you specific line where the test failed in your Spec file. I'd suggest that you eliminate any lines whose address starts with `at scala.` except possibly the first one, since these lines are generally the guts of the scala libraries (collections in particular) and rarely have any direct consequence in the failure. Eliminating these lines would be a meaningful list of top to bottom

**Comment by jackkoenig** [comment]
@chick, assuming Chisel still returns error, then ScalaTest or the chisel testers should still throw their own exceptions that include the stack trace of the invocation of the test? Perhaps I should try my proposal and see how it looks with the testers...

My proposed trimming removes 21 out of the 25 lines in @albertchen-sifive's originally proposal. I'm not sure what your proposed trimming would look like, but an alternative approach preserving some of the user invocation could trim further to something like:

```
[info] [0.003] Elaborating design...
[error] chisel3.core.Binding$ExpectedChiselTypeException: reg type 'chisel3.core.UInt@3400978d' must be a Chisel type, not hardware
[error]         ...
[error]         at NeedChiselType.$anonfun$delays$1(ChiselExceptionTest.scala:8)
[error]         at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[error]         at NeedChiselType.<init>(ChiselExceptionTest.scala:8)
[error]         at NeedChiselTypeTop$.$anonfun$code$1(ChiselExceptionTest.scala:17)
                ...
[error]         at NeedChiselTypeTop$.delayedEndpoint$NeedChiselTypeTop$1(ChiselExceptionTest.scala:17)
[error]         at NeedChiselTypeTop$delayedInit$body.apply(ChiselExceptionTest.scala:16)
                ...
[error]         at NeedChiselTypeTop$.main(ChiselExceptionTest.scala:16)
[error]         at NeedChiselTypeTop.main(ChiselExceptionTest.scala)
[error]         ... (Stack trace trimmed to user code only, rerun with --full-stacktrace if you wish to see the full stack trace)
```

I really think we should find a way to remove the 10 lines from `chisel3.Driver.execute` the outer `Module.do_apply` because it's mostly worthless for the user

**Comment by chick** [comment]
@jackkoenig Looking over things I am fine using your trimming strategy. I think it's nice if you can see the test where things originated, but I agree as little as possible of the Driver.execute stuff should be seen. I think it's been done here, but as little as possible of the scalatest stuff should show. IntelliJ grays out all this junky stuff, but not seeing it all would be better

**Pull request merged**
