### PR TITLE
Mainline Chisel multi-clock functionality

### LINKED ISSUE #1009: [RFC] Mainline withClockAndReset and friends out of experimental
**Type of issue**: feature request

**Impact**: API addition (no impact on existing code)

**Development Phase**: proposal

**Other information**
 
Currently Chisel's multi-clock support is contained in chisel3 experimental and has been there for almost 2 years now since #509. It appears that users are using this API, including in [rocket-chip](https://github.com/freechipsproject/rocket-chip/blob/2c1ad08b7fb9beb80634839bdcf0e914dadf11dc/src/main/scala/diplomacy/LazyModule.scala#L197). Mainlining this API into `chisel3._` may make this feature more discoverable and official since the API appears to be relatively stable and usable. Thoughts?

### PR DESCRIPTION
**Pull request by edwardcwang**
Close #1009

### CODE REVIEW

**Comment by edwardcwang** [comment]
```
[info] ScalaTest
[info] Run completed in 16 minutes, 47 seconds.
[info] Total number of tests run: 426
[info] Suites: completed 105, aborted 0
[info] Tests: succeeded 426, failed 0, canceled 0, ignored 16, pending 0
[info] All tests passed.
```

Chisel tests do seem to take a while to run

**Comment by edwardcwang** [comment]
@ucbjrl Do you know why Jenkins is spitting out a weird exception?

```
ERROR: Build step failed with exception
java.io.IOException: Cannot retrieve Git metadata for the build
	at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:87)
	at org.jenkinsci.plugins.github.status.sources.BuildDataRevisionShaSource.get(BuildDataRevisionShaSource.java:32)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:135)
```

**Comment by ucbjrl** [comment]
I suspect it's a GitHub communication issue. I'll re-deliver the pull request trigger.

**Comment by ucbjrl** [comment]
Hmmm. Still fails:
```
Finished Build : #1464 of Job : bare-chisel3-firrtl with status : SUCCESS
ERROR: [GitHub Commit Status Setter] Failed to update commit state on GitHub. Ignoring exception [Cannot retrieve Git metadata for the build]
```

**Comment by ucbjrl** [comment]
retest this please

**Comment by ucbjrl** [comment]
This continues to fail trying to update state on GitHub. It looks like the secret for this webhook may have been deleted. I'll try to resurrect it.

**Comment by edwardcwang** [comment]
Importing both appears to work - it just results in a deprecation warning from having imported e.g. `chisel3.experimental.withClockAndReset`.

**Pull request merged**
