### PR TITLE
add toTarget for NamedComponent, and Module, deprcate toNamed.

### PR DESCRIPTION
**Pull request by sequencer**
**Type of change**: other enhancement

**Impact**: API addition (no impact on existing code)

**Development Phase**: proposal

**Release Notes**
Since `Named` is deprecated in firrtl, It's more elegant to deprecate correspond `toNamed` in `chiselFrontend` with `toTarget`.

### CODE REVIEW

**Comment by ucbjrl** [comment]
ok to test

**Comment by sequencer** [comment]
After this modification
```
def toNamed = toTarget.toNamed
```
original `toNamed` test will also test `toTarget`, maybe not need to add more test for `toTarget`.

**Comment by sequencer** [comment]
@chick is that OK for deprecate in 3.1 like this?

**Comment by sequencer** [comment]
Is this ok for merge?

**Comment by sequencer** [comment]
@azidar implemented this PR in aop, closed

**Pull request closed without merging**
