### PR TITLE
Add ChiselEnum to BundleLiterals

### PR DESCRIPTION
**Pull request by zhuanhao-wu**
**Related issue**: #1214 

**Type of change**: other enhancement

**Impact**: API modification

**Development Phase**: implementation

**Release Notes**
This PR enables the use of EnumType in BundleLiterals. For example, the following code should work:
```scala
object ENUM extends ChiselEnum {
  val a, b, c = Value
}
class t extends Bundle {
  val a = ENUM()
}
class tIO extends Bundle {
  val a = Output(new t())
}
class TestModule extends Module {
  val io = IO(new tIO())

  io.a := (new t).Lit(_.a -> ENUM.b)
}
```

### CODE REVIEW

**Comment by ucbjrl** [comment]
ok to test

**Comment by jackkoenig** [comment]
@ducky64 should this be backported to 1.2.x?

**Comment by ducky64** [comment]
@jackkoenig I don't see why not.

**Comment by zhuanhao-wu** [comment]
@ducky64 sorry for blocking, I have signed the CLA, please proceed, thanks

**Pull request merged**
