### PR TITLE
Added support to extract bit in reverse order

### PR DESCRIPTION
**Pull request by bhimsenpadalkar**
**Type of change**: feature request

**Impact**: API modification

**Development Phase**: implementation

**Release Notes**

### CODE REVIEW

**Comment by seldridge** [comment]
ok to test

**Comment by ucbjrl** [comment]
retest this please

**Comment by bhimsenpadalkar** [comment]
Makes perfect sense.. Thanks !!

**Comment by jackkoenig** [comment]
I agree with @seldridge, I think an explicit reverse followed by extraction makes the most sense.

I would like to add that there is already a reverse utility: [`chisel3.util.Reverse`](https://github.com/freechipsproject/chisel3/blob/83f2a65a3ab1d21258883c0b113406ef9900a57f/src/main/scala/chisel3/util/Bitwise.scala#L92)

**Pull request closed without merging**
